### ISSUE TITLE
[pyro64-acpi|rocko64-acpi] flashall.sh successfully working on mini breakout board

### ISSUE THREAD

**Issue by vrubiolo** [htot/meta-intel-edison#19]
Hi there,

Just a note to report that I have been successfully able to use flashall.sh on my mini-breakout board to flash the pyro64-acpi produced kernel and rootfs. I had previously updated u-boot as per the wiki but I am not sure this is necessary as flashall seems to be taking care of that too.
This is a great milestone! Thanks much for the hard work, I could not wait to share that:)
Now onto moving to rocko64 ..

Attached is my [boot log](https://github.com/htot/meta-intel-edison/files/1959712/new_kernel_boot_success.txt), I can provide more information if you need me to.

Edit: this is not an issue of course, I would like to add a label and switch it to a question/observation but I don't know how I can do that.

**Comment by htot** [comment]
Good news. I guess eth over usb won't be working yet as we force it to host mode. Maybe in 4.17?

**Comment by vrubiolo** [comment]
And I confirm I could also boot the image using the rocko64-acpi branch. [Here](https://github.com/htot/meta-intel-edison/files/1990095/new_kernel_boot_success-kernel_v4.16.txt) is the associated boot log. Great job!
